// <auto-generated />
namespace CeeLearnAndDo.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class VraagbaakV28 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(VraagbaakV28));
        
        string IMigrationMetadata.Id
        {
            get { return "201804241418458_VraagbaakV28"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
